- name: app setup
  ansible.builtin.import_role:
    name: app-setup
    tasks_from: app-setup.yaml

- name: nodejs setup
  ansible.builtin.import_role:
    name: nodejs-setup
    tasks_from: nodejs-setup.yaml

- name: system-setup setup
  ansible.builtin.import_role:
    name: common
    tasks_from: system-setup.yaml
  
